name: Kernel Compilation

on:
  workflow_dispatch:
    inputs:      
      tag:
        description: 'Release Version Tag'
        required: true    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up build environment
      run: |
        sudo apt update -y  
        sudo apt install libncurses5-dev -y

    - name: Set environment variable
      run: |
        echo "BUILD_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV 

    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup KernelSU-Next
      run: |
        if [ -d "./KernelSU-Next" ]; then rm -rf "./KernelSU-Next"; fi
        if [ -d "./drivers/KernelSU-Next" ]; then rm -rf "./drivers/KernelSU-Next"; fi 
        curl -LSs "https://raw.githubusercontent.com/Star-Seven/KernelSU-Next/next/kernel/setup.sh" | bash -

    - name: Setup and Apply KernelSU-Next Patches
      run: |
           set -e

           # Backport SUSFS to Linux 4.14
           git clone https://github.com/Star-Seven/susfs4ksu -b M62-backport-Susfs susfs4ksu-repo

           cp susfs4ksu-repo/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
           cd ./KernelSU-Next
           patch -p1 -F 3 < 10_enable_susfs_for_ksu.patch || { echo "Failed to apply patch"; exit 1; }
           echo "Successfully applied KSUN patches"
           
    - name: Compile Kernel
      run: |
        bash build_kernel.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KernelSU-Next-SM-A047F-${{ github.event.inputs.tag }}
        path: build/*.tar

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.inputs.tag }}
        name: "KernelSU-Next-SM-A047F-${{ github.event.inputs.tag }}"
        draft: false
        prerelease: false
        token: ${{ secrets.TOKEN }}          
        artifacts: "build/*.tar"
        body: "Commit SHA: ${{ github.sha }}"
